"""initial schema: 42 tables (Stage 0/EPIC-A/B)

Revision ID: aeaea900e099
Revises: 
Create Date: 2026-08-28 13:25:10.363489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeaea900e099'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('SCENE_GENOME', 'CHARACTER_TIMELINE', 'CAUSAL_GRAPH', 'TECHNIQUE_CARD', 'HYPOTHESIS_REPORT', 'EXPERIMENT_REPORT', 'ROLLOUT_TREE', 'BENCHMARK_RESULT', 'REPORT', 'RAW_OUTPUT', name='artifacttype'), nullable=False),
    sa.Column('parent_type', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('source_class', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_patterns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=256), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.Column('candidate_actions', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OBSERVATION', 'CANDIDATE', 'SUPPORTED', 'REPLICATED', 'VALIDATED', 'PRODUCTION_PROVEN', 'REJECTED', 'DEPRECATED', name='knowledgetier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bench', sa.Enum('CHARACTER_BENCH', 'CAUSAL_BENCH', 'EMOTION_BENCH', 'INFO_GAP_BENCH', 'SUSPENSE_BENCH', 'LONG_STORY_BENCH', name='benchname'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('input_ref', sa.JSON(), nullable=False),
    sa.Column('expected', sa.JSON(), nullable=False),
    sa.Column('gold', sa.Boolean(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('source_class', sa.Enum('HUMAN_ORIGINAL', 'HUMAN_EDITED', 'AI_GENERATED', 'AI_REWRITTEN', 'EXPERIMENTAL_COUNTERFACTUAL', 'PRODUCTION_NOVELFORGE', 'USER_FEEDBACK', name='sourceclass'), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('predicate', sa.String(length=256), nullable=False),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('agent_run', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_packages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=128), nullable=False),
    sa.Column('source_scene_id', sa.String(length=64), nullable=True),
    sa.Column('neighbor_scenes', sa.JSON(), nullable=False),
    sa.Column('relevant_character_states', sa.JSON(), nullable=False),
    sa.Column('relevant_facts', sa.JSON(), nullable=False),
    sa.Column('active_relationships', sa.JSON(), nullable=False),
    sa.Column('active_foreshadows', sa.JSON(), nullable=False),
    sa.Column('prior_claims', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('retrieval_results', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('source_class', sa.Enum('HUMAN_ORIGINAL', 'HUMAN_EDITED', 'AI_GENERATED', 'AI_REWRITTEN', 'EXPERIMENTAL_COUNTERFACTUAL', 'PRODUCTION_NOVELFORGE', 'USER_FEEDBACK', name='sourceclass'), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('raw_path', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_letter',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('original_task_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('PAIRWISE', 'ABSOLUTE', 'READER_SIM', 'RULE_EVAL', 'BENCHMARK', name='evaluationtype'), nullable=False),
    sa.Column('subject_a_ref', sa.String(length=256), nullable=True),
    sa.Column('subject_b_ref', sa.String(length=256), nullable=True),
    sa.Column('winner', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decisive_dimensions', sa.JSON(), nullable=False),
    sa.Column('evidence_spans', sa.JSON(), nullable=False),
    sa.Column('failure_reasons', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('blind', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('independent_variables', sa.JSON(), nullable=False),
    sa.Column('dependent_variables', sa.JSON(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expected_direction', sa.Text(), nullable=True),
    sa.Column('falsification_condition', sa.Text(), nullable=True),
    sa.Column('origin_evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'TESTING', 'SUPPORTED', 'REJECTED', 'REPLICATED', name='hypothesisstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('capability_tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_registry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=256), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('model_class', sa.String(length=64), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('benchmark_result', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('patience', sa.Float(), nullable=False),
    sa.Column('pacing_preference', sa.Float(), nullable=False),
    sa.Column('novelty_preference', sa.Float(), nullable=False),
    sa.Column('logic_sensitivity', sa.Float(), nullable=False),
    sa.Column('prose_sensitivity', sa.Float(), nullable=False),
    sa.Column('character_attachment_weight', sa.Float(), nullable=False),
    sa.Column('romance_weight', sa.Float(), nullable=False),
    sa.Column('suspense_weight', sa.Float(), nullable=False),
    sa.Column('action_weight', sa.Float(), nullable=False),
    sa.Column('erotic_tension_weight', sa.Float(), nullable=False),
    sa.Column('tolerance_for_repetition', sa.Float(), nullable=False),
    sa.Column('tolerance_for_coincidence', sa.Float(), nullable=False),
    sa.Column('tolerance_for_exposition', sa.Float(), nullable=False),
    sa.Column('cliffhanger_preference', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('from_type', sa.String(length=64), nullable=False),
    sa.Column('from_id', sa.String(length=64), nullable=False),
    sa.Column('to_type', sa.String(length=64), nullable=False),
    sa.Column('to_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('CONTAINS', 'OBSERVED_IN', 'SUPPORTS', 'CONTRADICTS', 'DERIVED_FROM', 'TESTS', 'CAUSES', 'AFFECTS', 'APPLIES_TO', 'FAILS_IN', 'REPLICATES', name='researchedgetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=128), nullable=False),
    sa.Column('parent_task', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('context_package_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'RUNNING', 'WAITING', 'SUCCESS', 'PARTIAL', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('input_ref', sa.JSON(), nullable=False),
    sa.Column('output_ref', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('queue', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'RUNNING', 'WAITING', 'SUCCESS', 'PARTIAL', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('techniques',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.Enum('INFORMATION', 'SUSPENSE', 'MYSTERY', 'FORESHADOW', 'REVEAL', 'PAYOFF', 'CONFLICT', 'ESCALATION', 'CHARACTERIZATION', 'RELATIONSHIP', 'EMOTION', 'PACING', 'DIALOGUE', 'POV', 'SCENE_STRUCTURE', 'CHAPTER_HOOK', 'WORLDBUILDING', 'ACTION', 'COMEDY', 'HORROR', 'ROMANCE', 'EROTIC_TENSION', 'TRAGEDY', 'TWIST', 'MISDIRECTION', 'REWARD', 'LOSS', 'PROGRESSION', 'POWER_FANTASY', name='techniquecategory'), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.JSON(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('execution', sa.JSON(), nullable=False),
    sa.Column('expected_effects', sa.JSON(), nullable=False),
    sa.Column('failure_modes', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('counterexamples', sa.JSON(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('experiment_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OBSERVATION', 'CANDIDATE', 'SUPPORTED', 'REPLICATED', 'VALIDATED', 'PRODUCTION_PROVEN', 'REJECTED', 'DEPRECATED', name='knowledgetier'), nullable=False),
    sa.Column('source_class', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.JSON(), nullable=False),
    sa.Column('taste_vector', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bench', sa.Enum('CHARACTER_BENCH', 'CAUSAL_BENCH', 'EMOTION_BENCH', 'INFO_GAP_BENCH', 'SUSPENSE_BENCH', 'LONG_STORY_BENCH', name='benchname'), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('subject_ref', sa.String(length=256), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['benchmark_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('corpus_source_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_source_id'], ['corpus_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('DIRECT_TEXT', 'DIALOGUE', 'BEHAVIOR', 'NARRATION', 'STATE_TRANSITION', 'CROSS_SCENE', 'EXTERNAL_ANNOTATION', 'HUMAN_FEEDBACK', 'EXPERIMENTAL_RESULT', name='evidencetype'), nullable=False),
    sa.Column('source_span_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('external_ref', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=False),
    sa.Column('fixed', sa.JSON(), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=False),
    sa.Column('falsification', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DESIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', name='experimentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('INFORMATION', 'SUSPENSE', 'MYSTERY', 'FORESHADOW', 'REVEAL', 'PAYOFF', 'CONFLICT', 'ESCALATION', 'CHARACTERIZATION', 'RELATIONSHIP', 'EMOTION', 'PACING', 'DIALOGUE', 'POV', 'SCENE_STRUCTURE', 'CHAPTER_HOOK', 'WORLDBUILDING', 'ACTION', 'COMEDY', 'HORROR', 'ROMANCE', 'EROTIC_TENSION', 'TRAGEDY', 'TWIST', 'MISDIRECTION', 'REWARD', 'LOSS', 'PROGRESSION', 'POWER_FANTASY', name='techniquecategory'), nullable=True),
    sa.Column('tier', sa.Enum('OBSERVATION', 'CANDIDATE', 'SUPPORTED', 'REPLICATED', 'VALIDATED', 'PRODUCTION_PROVEN', 'REJECTED', 'DEPRECATED', name='knowledgetier'), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('failure_modes', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('counterexamples', sa.JSON(), nullable=False),
    sa.Column('experiment_ids', sa.JSON(), nullable=False),
    sa.Column('reproduction_count', sa.Integer(), nullable=False),
    sa.Column('judge_agreement', sa.Float(), nullable=False),
    sa.Column('production_evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['techniques.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('parent_task', sa.String(length=64), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('derived_artifacts', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causal_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('from_id', sa.String(length=64), nullable=False),
    sa.Column('to_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('PHYSICAL_CAUSE', 'INFORMATIONAL_CAUSE', 'PSYCHOLOGICAL_CAUSE', 'SOCIAL_CAUSE', 'RESOURCE_CAUSE', 'GOAL_CAUSE', 'CONSTRAINT_CAUSE', 'AUTHORIAL_STRUCTURE', 'TEMPORAL_ONLY', 'CORRELATION_ONLY', name='causaledgetype'), nullable=False),
    sa.Column('necessity', sa.Float(), nullable=False),
    sa.Column('sufficiency', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('identity', sa.JSON(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('habits', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('taboos', sa.JSON(), nullable=False),
    sa.Column('long_term_desires', sa.JSON(), nullable=False),
    sa.Column('core_fears', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_variants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('variant_type', sa.Enum('CONTROL', 'TREATMENT', name='varianttype'), nullable=False),
    sa.Column('changed', sa.JSON(), nullable=False),
    sa.Column('fixed', sa.JSON(), nullable=False),
    sa.Column('measured', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('chapter_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('pov', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('scene_goal', sa.Text(), nullable=True),
    sa.Column('dominant_conflict', sa.String(length=256), nullable=True),
    sa.Column('narrative_functions', sa.JSON(), nullable=False),
    sa.Column('entry_state', sa.JSON(), nullable=False),
    sa.Column('exit_state', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_range', sa.JSON(), nullable=False),
    sa.Column('genome', sa.JSON(), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belief_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('proposition', sa.Text(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('beliefs', sa.JSON(), nullable=False),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('desires', sa.JSON(), nullable=False),
    sa.Column('fears', sa.JSON(), nullable=False),
    sa.Column('emotions', sa.JSON(), nullable=False),
    sa.Column('commitments', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('derived_from_state_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('object', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('INTERNAL', 'INTERPERSONAL', 'EXTERNAL', 'SOCIETAL', name='conflicttype'), nullable=False),
    sa.Column('stakes', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('asymmetry', sa.Text(), nullable=True),
    sa.Column('possible_resolutions', sa.JSON(), nullable=False),
    sa.Column('current_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_span_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('planted_scene_id', sa.String(length=64), nullable=True),
    sa.Column('target_payoff', sa.String(length=256), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.Column('reader_awareness', sa.String(length=32), nullable=True),
    sa.Column('character_awareness', sa.JSON(), nullable=False),
    sa.Column('reinforcement_scenes', sa.JSON(), nullable=False),
    sa.Column('expected_payoff_window', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planted_scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information_gaps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=True),
    sa.Column('reader_knows', sa.Boolean(), nullable=False),
    sa.Column('character_knows', sa.JSON(), nullable=False),
    sa.Column('character_does_not_know', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=True),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'EXPOSED', 'SUSPECTED', 'BELIEVED', 'KNOWN', 'DISBELIEVED', 'FALSE_BELIEF', 'FORGOTTEN', 'AMBIGUOUS', name='knowledgestatus'), nullable=False),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('acquisition_event_id', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('from_character_id', sa.String(length=64), nullable=False),
    sa.Column('to_character_id', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_spans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('annotation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotion_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('emotion', sa.Enum('ANGER', 'SADNESS', 'FEAR', 'JOY', 'ANXIETY', 'SHAME', 'GUILT', 'JEALOUSY', 'HOPE', 'DISAPPOINTMENT', 'SURPRISE', 'CONTEMPT', 'PRIDE', 'RELIEF', 'CURIOSITY', 'TENDERNESS', 'CONFUSION', 'NUMBNESS', name='emotiontype'), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=64), nullable=True),
    sa.Column('appraisal', sa.JSON(), nullable=False),
    sa.Column('action_tendency', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payoffs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('foreshadow_id', sa.String(length=64), nullable=True),
    sa.Column('scene_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadow_id'], ['foreshadows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perceptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('perceived_event_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perceived_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perceptions')
    op.drop_table('payoffs')
    op.drop_table('emotion_states')
    op.drop_table('scene_spans')
    op.drop_table('relationship_states')
    op.drop_table('knowledge_states')
    op.drop_table('information_gaps')
    op.drop_table('goals')
    op.drop_table('foreshadows')
    op.drop_table('events')
    op.drop_table('conflicts')
    op.drop_table('character_states')
    op.drop_table('belief_states')
    op.drop_table('scenes')
    op.drop_table('facts')
    op.drop_table('experiment_variants')
    op.drop_table('characters')
    op.drop_table('chapters')
    op.drop_table('causal_edges')
    op.drop_table('model_calls')
    op.drop_table('knowledge_rules')
    op.drop_table('experiments')
    op.drop_table('evidence')
    op.drop_table('books')
    op.drop_table('benchmark_runs')
    op.drop_table('user_feedback')
    op.drop_table('techniques')
    op.drop_table('tasks')
    op.drop_table('runs')
    op.drop_table('research_edges')
    op.drop_table('reader_profiles')
    op.drop_table('prompt_registry')
    op.drop_table('model_registry')
    op.drop_table('hypotheses')
    op.drop_table('evaluations')
    op.drop_table('dead_letter')
    op.drop_table('corpus_sources')
    op.drop_table('context_packages')
    op.drop_table('claims')
    op.drop_table('benchmark_cases')
    op.drop_table('behavior_patterns')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
