"""initial schema

Revision ID: 60282021bafa
Revises: 
Create Date: 2026-05-30 15:35:18.475915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60282021bafa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author_alias', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('target_usage', sa.String(length=200), nullable=True),
    sa.Column('analysis_progress', sa.Integer(), nullable=True),
    sa.Column('analysis_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_table('knowledge_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('pattern_name', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applicable_scene', sa.Text(), nullable=True),
    sa.Column('anti_patterns', sa.Text(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_patterns_genre'), 'knowledge_patterns', ['genre'], unique=False)
    op.create_index(op.f('ix_knowledge_patterns_id'), 'knowledge_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_patterns_pattern_type'), 'knowledge_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_knowledge_patterns_tag'), 'knowledge_patterns', ['tag'], unique=False)
    op.create_table('model_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_mask', sa.String(length=100), nullable=True),
    sa.Column('default_model', sa.String(length=200), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('default_temperature', sa.Float(), nullable=True),
    sa.Column('default_top_p', sa.Float(), nullable=True),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_times', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_providers_id'), 'model_providers', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('target_reader', sa.String(length=200), nullable=True),
    sa.Column('total_word_goal', sa.Integer(), nullable=True),
    sa.Column('daily_word_goal', sa.Integer(), nullable=True),
    sa.Column('chapter_word_goal', sa.Integer(), nullable=True),
    sa.Column('daily_chapter_goal', sa.Integer(), nullable=True),
    sa.Column('update_time_slots', sa.JSON(), nullable=True),
    sa.Column('plot_progress_intensity', sa.Integer(), nullable=True),
    sa.Column('satisfaction_density', sa.Integer(), nullable=True),
    sa.Column('emotional_tension', sa.Integer(), nullable=True),
    sa.Column('writing_delicacy', sa.Integer(), nullable=True),
    sa.Column('dialogue_ratio', sa.Integer(), nullable=True),
    sa.Column('description_ratio', sa.Integer(), nullable=True),
    sa.Column('commercial_pace', sa.Integer(), nullable=True),
    sa.Column('adult_content_scale', sa.Integer(), nullable=True),
    sa.Column('forbidden_settings', sa.JSON(), nullable=True),
    sa.Column('forbidden_relationships', sa.JSON(), nullable=True),
    sa.Column('forbidden_plots', sa.JSON(), nullable=True),
    sa.Column('forbidden_genres', sa.JSON(), nullable=True),
    sa.Column('technique_cards', sa.JSON(), nullable=True),
    sa.Column('excluded_techniques', sa.JSON(), nullable=True),
    sa.Column('preferred_template', sa.String(length=100), nullable=True),
    sa.Column('quality_threshold', sa.Integer(), nullable=True),
    sa.Column('quality_priority', sa.String(length=20), nullable=True),
    sa.Column('max_rewrite_rounds', sa.Integer(), nullable=True),
    sa.Column('rewrite_improvement_threshold', sa.Float(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_chapter_index', sa.Integer(), nullable=True),
    sa.Column('total_words_written', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('prompt_evolution_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('min_sample_count', sa.Integer(), nullable=True),
    sa.Column('min_average_score', sa.Float(), nullable=True),
    sa.Column('max_rewrite_rate', sa.Float(), nullable=True),
    sa.Column('trigger_window_days', sa.Integer(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('ab_test_sample_count', sa.Integer(), nullable=True),
    sa.Column('min_improvement', sa.Float(), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('rollout_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_evolution_policies_id'), 'prompt_evolution_policies', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_evolution_policies_role'), 'prompt_evolution_policies', ['role'], unique=False)
    op.create_table('reader_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('insight_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reader_insights_genre'), 'reader_insights', ['genre'], unique=False)
    op.create_index(op.f('ix_reader_insights_id'), 'reader_insights', ['id'], unique=False)
    op.create_index(op.f('ix_reader_insights_insight_type'), 'reader_insights', ['insight_type'], unique=False)
    op.create_table('story_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure_steps', sa.JSON(), nullable=True),
    sa.Column('expected_length', sa.String(length=100), nullable=True),
    sa.Column('usable_for', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_patterns_id'), 'story_patterns', ['id'], unique=False)
    op.create_table('trend_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('report_title', sa.String(length=255), nullable=False),
    sa.Column('report_body', sa.Text(), nullable=False),
    sa.Column('trend_tags', sa.JSON(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_reports_genre'), 'trend_reports', ['genre'], unique=False)
    op.create_index(op.f('ix_trend_reports_id'), 'trend_reports', ['id'], unique=False)
    op.create_index(op.f('ix_trend_reports_platform'), 'trend_reports', ['platform'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('budget_tokens', sa.Integer(), nullable=True),
    sa.Column('budget_cost', sa.Float(), nullable=True),
    sa.Column('used_tokens', sa.Integer(), nullable=True),
    sa.Column('used_cost', sa.Float(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=True),
    sa.Column('final_report', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('book_analysis_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('avg_chapter_words', sa.Float(), nullable=True),
    sa.Column('chapter_word_std', sa.Float(), nullable=True),
    sa.Column('hook_rate', sa.Float(), nullable=True),
    sa.Column('cliffhanger_rate', sa.Float(), nullable=True),
    sa.Column('payoff_cadence_chapters', sa.Float(), nullable=True),
    sa.Column('emotion_curve', sa.JSON(), nullable=True),
    sa.Column('pacing_rules', sa.JSON(), nullable=True),
    sa.Column('character_arc_patterns', sa.JSON(), nullable=True),
    sa.Column('plot_structure', sa.JSON(), nullable=True),
    sa.Column('satisfaction_peaks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_analysis_profiles_book_id'), 'book_analysis_profiles', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_analysis_profiles_id'), 'book_analysis_profiles', ['id'], unique=False)
    op.create_table('book_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('structure_analysis', sa.JSON(), nullable=True),
    sa.Column('character_mentions', sa.JSON(), nullable=True),
    sa.Column('plot_points', sa.JSON(), nullable=True),
    sa.Column('emotional_beats', sa.JSON(), nullable=True),
    sa.Column('hooks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_chapters_id'), 'book_chapters', ['id'], unique=False)
    op.create_table('book_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('sub_genre', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('narrative_pov', sa.String(length=50), nullable=True),
    sa.Column('pacing_type', sa.String(length=50), nullable=True),
    sa.Column('commercial_density', sa.Integer(), nullable=True),
    sa.Column('adult_level', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('reusable_skill_categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_index(op.f('ix_book_profiles_id'), 'book_profiles', ['id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('final_word_count', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('plot_progress_score', sa.Float(), nullable=True),
    sa.Column('character_consistency_score', sa.Float(), nullable=True),
    sa.Column('pacing_score', sa.Float(), nullable=True),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('emotional_reward_score', sa.Float(), nullable=True),
    sa.Column('style_consistency_score', sa.Float(), nullable=True),
    sa.Column('continuity_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('best_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_table('character_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('stable_profile', sa.JSON(), nullable=True),
    sa.Column('dynamic_state', sa.JSON(), nullable=True),
    sa.Column('personality', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('last_seen_chapter', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('latest_update_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_char_memory_importance', 'character_memories', ['project_id', 'importance_score'], unique=False)
    op.create_index('idx_char_memory_project_name', 'character_memories', ['project_id', 'name'], unique=False)
    op.create_index(op.f('ix_character_memories_id'), 'character_memories', ['id'], unique=False)
    op.create_index(op.f('ix_character_memories_name'), 'character_memories', ['name'], unique=False)
    op.create_index(op.f('ix_character_memories_project_id'), 'character_memories', ['project_id'], unique=False)
    op.create_table('consistency_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('CHARACTER', 'POWER', 'TIMELINE', 'WORLD_SETTING', 'RELATIONSHIP', 'LOCATION', 'ITEM', name='consistencychecktype'), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_config', sa.JSON(), nullable=True),
    sa.Column('auto_check', sa.Boolean(), nullable=True),
    sa.Column('check_frequency', sa.String(length=20), nullable=True),
    sa.Column('alert_threshold', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'INFO', name='consistencyissueseverity'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_rules_id'), 'consistency_rules', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_rules_project_id'), 'consistency_rules', ['project_id'], unique=False)
    op.create_table('failure_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('prevention_rule', sa.Text(), nullable=True),
    sa.Column('example_note', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_patterns_id'), 'failure_patterns', ['id'], unique=False)
    op.create_table('foreshadows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('foreshadow_type', sa.String(length=100), nullable=True),
    sa.Column('setup_chapter', sa.Integer(), nullable=True),
    sa.Column('expected_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('actual_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('setup_content', sa.Text(), nullable=True),
    sa.Column('development_notes', sa.JSON(), nullable=True),
    sa.Column('payoff_plan', sa.Text(), nullable=True),
    sa.Column('payoff_content', sa.Text(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_items', sa.JSON(), nullable=True),
    sa.Column('related_world_rules', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reader_expectation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_foreshadow_project_status', 'foreshadows', ['project_id', 'status'], unique=False)
    op.create_index('idx_foreshadow_setup_chapter', 'foreshadows', ['project_id', 'setup_chapter'], unique=False)
    op.create_index(op.f('ix_foreshadows_id'), 'foreshadows', ['id'], unique=False)
    op.create_index(op.f('ix_foreshadows_project_id'), 'foreshadows', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadows_setup_chapter'), 'foreshadows', ['setup_chapter'], unique=False)
    op.create_index(op.f('ix_foreshadows_status'), 'foreshadows', ['status'], unique=False)
    op.create_table('model_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_summary', sa.Text(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_call_logs_id'), 'model_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_model_call_logs_project_id'), 'model_call_logs', ['project_id'], unique=False)
    op.create_table('model_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_roles_id'), 'model_roles', ['id'], unique=False)
    op.create_table('novel_bibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('world_setting', sa.Text(), nullable=True),
    sa.Column('world_rules', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('characters', sa.JSON(), nullable=True),
    sa.Column('character_relationships', sa.JSON(), nullable=True),
    sa.Column('main_plot', sa.Text(), nullable=True),
    sa.Column('sub_plots', sa.JSON(), nullable=True),
    sa.Column('foreshadowing', sa.JSON(), nullable=True),
    sa.Column('style_boundaries', sa.JSON(), nullable=True),
    sa.Column('tone_guidelines', sa.Text(), nullable=True),
    sa.Column('forbidden_items', sa.JSON(), nullable=True),
    sa.Column('volume_outline', sa.JSON(), nullable=True),
    sa.Column('chapter_outline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_novel_bibles_id'), 'novel_bibles', ['id'], unique=False)
    op.create_table('production_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('target_daily_words', sa.Integer(), nullable=True),
    sa.Column('target_daily_chapters', sa.Integer(), nullable=True),
    sa.Column('max_daily_cost', sa.Float(), nullable=True),
    sa.Column('max_daily_tokens', sa.Integer(), nullable=True),
    sa.Column('min_quality_score', sa.Float(), nullable=True),
    sa.Column('max_rewrite_rounds', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('auto_create_next_chapter', sa.Integer(), nullable=True),
    sa.Column('auto_pause_on_failure', sa.Integer(), nullable=True),
    sa.Column('auto_pause_on_budget', sa.Integer(), nullable=True),
    sa.Column('active_hours', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_policies_id'), 'production_policies', ['id'], unique=False)
    op.create_index(op.f('ix_production_policies_project_id'), 'production_policies', ['project_id'], unique=True)
    op.create_table('production_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('chapters_completed', sa.Integer(), nullable=True),
    sa.Column('words_written', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('rewrite_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('word_goal_achievement', sa.Float(), nullable=True),
    sa.Column('chapter_goal_achievement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_stats_project_date', 'production_stats', ['project_id', 'date'], unique=True)
    op.create_index(op.f('ix_production_stats_date'), 'production_stats', ['date'], unique=False)
    op.create_index(op.f('ix_production_stats_id'), 'production_stats', ['id'], unique=False)
    op.create_index(op.f('ix_production_stats_project_id'), 'production_stats', ['project_id'], unique=False)
    op.create_table('project_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_books', sa.JSON(), nullable=True),
    sa.Column('source_techniques', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('style_boundaries', sa.Text(), nullable=True),
    sa.Column('tone_guidelines', sa.Text(), nullable=True),
    sa.Column('chapter_template', sa.JSON(), nullable=True),
    sa.Column('scoring_rubric', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_project_playbooks_id'), 'project_playbooks', ['id'], unique=False)
    op.create_table('prompt_evolution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('failure_samples_json', sa.JSON(), nullable=True),
    sa.Column('candidate_prompts_json', sa.JSON(), nullable=True),
    sa.Column('ab_test_result_json', sa.JSON(), nullable=True),
    sa.Column('applied_prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['prompt_evolution_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_evolution_runs_id'), 'prompt_evolution_runs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_evolution_runs_policy_id'), 'prompt_evolution_runs', ['policy_id'], unique=False)
    op.create_index(op.f('ix_prompt_evolution_runs_role'), 'prompt_evolution_runs', ['role'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables_schema', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_role'), 'prompt_templates', ['role'], unique=False)
    op.create_table('provider_route_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_reset_seconds', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_opened_at', sa.DateTime(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('success_calls', sa.Integer(), nullable=True),
    sa.Column('failed_calls', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_route_configs_id'), 'provider_route_configs', ['id'], unique=False)
    op.create_index(op.f('ix_provider_route_configs_provider_id'), 'provider_route_configs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_route_configs_role'), 'provider_route_configs', ['role'], unique=False)
    op.create_table('relationship_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_a', sa.String(length=200), nullable=True),
    sa.Column('character_b', sa.String(length=200), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('tension_level', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('last_changed_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_memory_project_chars', 'relationship_memories', ['project_id', 'character_a', 'character_b'], unique=False)
    op.create_index(op.f('ix_relationship_memories_character_a'), 'relationship_memories', ['character_a'], unique=False)
    op.create_index(op.f('ix_relationship_memories_character_b'), 'relationship_memories', ['character_b'], unique=False)
    op.create_index(op.f('ix_relationship_memories_id'), 'relationship_memories', ['id'], unique=False)
    op.create_index(op.f('ix_relationship_memories_project_id'), 'relationship_memories', ['project_id'], unique=False)
    op.create_table('review_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('reviewer_roles', sa.JSON(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=True),
    sa.Column('rewrite_threshold', sa.Float(), nullable=True),
    sa.Column('auto_reject_threshold', sa.Float(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('strictness', sa.Integer(), nullable=True),
    sa.Column('max_review_rounds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_profiles_id'), 'review_profiles', ['id'], unique=False)
    op.create_table('technique_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('taxonomy_level_1', sa.String(length=100), nullable=True),
    sa.Column('taxonomy_level_2', sa.String(length=100), nullable=True),
    sa.Column('scene_stage', sa.String(length=100), nullable=True),
    sa.Column('suitable_chapter_range', sa.JSON(), nullable=True),
    sa.Column('source_book_type', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('source_chapters', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('principle', sa.Text(), nullable=True),
    sa.Column('transfer_rule', sa.Text(), nullable=True),
    sa.Column('usage_instruction', sa.Text(), nullable=True),
    sa.Column('anti_pattern', sa.Text(), nullable=True),
    sa.Column('prevention_rule', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('positive_review_count', sa.Integer(), nullable=True),
    sa.Column('negative_review_count', sa.Integer(), nullable=True),
    sa.Column('used_in_chapters', sa.JSON(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('prompt_instruction', sa.Text(), nullable=True),
    sa.Column('applicable_genres', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technique_cards_id'), 'technique_cards', ['id'], unique=False)
    op.create_index(op.f('ix_technique_cards_taxonomy_level_1'), 'technique_cards', ['taxonomy_level_1'], unique=False)
    op.create_index(op.f('ix_technique_cards_taxonomy_level_2'), 'technique_cards', ['taxonomy_level_2'], unique=False)
    op.create_table('version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_history_id'), 'version_history', ['id'], unique=False)
    op.create_table('world_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_chapters', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_canon', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_world_memory_project_cat', 'world_memories', ['project_id', 'category'], unique=False)
    op.create_index('idx_world_memory_project_name', 'world_memories', ['project_id', 'name'], unique=False)
    op.create_index(op.f('ix_world_memories_category'), 'world_memories', ['category'], unique=False)
    op.create_index(op.f('ix_world_memories_id'), 'world_memories', ['id'], unique=False)
    op.create_index(op.f('ix_world_memories_name'), 'world_memories', ['name'], unique=False)
    op.create_index(op.f('ix_world_memories_project_id'), 'world_memories', ['project_id'], unique=False)
    op.create_table('agent_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('planner_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_plans_id'), 'agent_plans', ['id'], unique=False)
    op.create_index(op.f('ix_agent_plans_run_id'), 'agent_plans', ['run_id'], unique=False)
    op.create_table('chapter_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('character_changes', sa.JSON(), nullable=True),
    sa.Column('world_updates', sa.JSON(), nullable=True),
    sa.Column('relationship_changes', sa.JSON(), nullable=True),
    sa.Column('unresolved_questions', sa.JSON(), nullable=True),
    sa.Column('foreshadow_updates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_memory_project_idx', 'chapter_memories', ['project_id', 'chapter_index'], unique=False)
    op.create_index(op.f('ix_chapter_memories_chapter_id'), 'chapter_memories', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_memories_chapter_index'), 'chapter_memories', ['chapter_index'], unique=False)
    op.create_index(op.f('ix_chapter_memories_id'), 'chapter_memories', ['id'], unique=False)
    op.create_index(op.f('ix_chapter_memories_project_id'), 'chapter_memories', ['project_id'], unique=False)
    op.create_table('chapter_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('plan_content', sa.Text(), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('critic_report', sa.Text(), nullable=True),
    sa.Column('continuity_report', sa.Text(), nullable=True),
    sa.Column('rewrite_count', sa.Integer(), nullable=True),
    sa.Column('improvement_from_last', sa.Float(), nullable=True),
    sa.Column('is_accepted', sa.Integer(), nullable=True),
    sa.Column('acceptance_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_versions_id'), 'chapter_versions', ['id'], unique=False)
    op.create_table('character_consistency_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_consistency_logs_chapter_id'), 'character_consistency_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_character_name'), 'character_consistency_logs', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_id'), 'character_consistency_logs', ['id'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_project_id'), 'character_consistency_logs', ['project_id'], unique=False)
    op.create_table('consistency_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('checked_chapters', sa.JSON(), nullable=True),
    sa.Column('check_scope', sa.String(length=50), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('major_count', sa.Integer(), nullable=True),
    sa.Column('minor_count', sa.Integer(), nullable=True),
    sa.Column('info_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['consistency_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_check_results_chapter_id'), 'consistency_check_results', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_id'), 'consistency_check_results', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_project_id'), 'consistency_check_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_rule_id'), 'consistency_check_results', ['rule_id'], unique=False)
    op.create_table('evolution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('before_version', sa.Text(), nullable=True),
    sa.Column('after_version', sa.Text(), nullable=True),
    sa.Column('before_score', sa.Float(), nullable=True),
    sa.Column('after_score', sa.Float(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('before_version_id', sa.Integer(), nullable=True),
    sa.Column('after_version_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('test_sample_count', sa.Integer(), nullable=True),
    sa.Column('judge_agents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['after_version_id'], ['version_history.id'], ),
    sa.ForeignKeyConstraint(['before_version_id'], ['version_history.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_runs_id'), 'evolution_runs', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_category', sa.String(length=100), nullable=True),
    sa.Column('parsed_rule', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('score_impact', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('is_applied', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('foreshadow_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('new_foreshadows', sa.JSON(), nullable=True),
    sa.Column('develop_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('payoff_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('must_include_lines', sa.JSON(), nullable=True),
    sa.Column('risky_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('is_executed', sa.Integer(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadow_plans_chapter_id'), 'foreshadow_plans', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadow_plans_chapter_index'), 'foreshadow_plans', ['chapter_index'], unique=False)
    op.create_index(op.f('ix_foreshadow_plans_project_id'), 'foreshadow_plans', ['project_id'], unique=False)
    op.create_table('foreshadow_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('forgotten_foreshadows', sa.JSON(), nullable=True),
    sa.Column('premature_payoffs', sa.JSON(), nullable=True),
    sa.Column('delayed_payoffs', sa.JSON(), nullable=True),
    sa.Column('payoff_quality_issues', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('foreshadow_score', sa.Float(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadow_reviews_chapter_id'), 'foreshadow_reviews', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadow_reviews_project_id'), 'foreshadow_reviews', ['project_id'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_agent', sa.String(length=100), nullable=True),
    sa.Column('model_config_id', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_id'), 'generation_tasks', ['id'], unique=False)
    op.create_table('memory_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_query_logs_chapter_id'), 'memory_query_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_memory_query_logs_id'), 'memory_query_logs', ['id'], unique=False)
    op.create_index(op.f('ix_memory_query_logs_project_id'), 'memory_query_logs', ['project_id'], unique=False)
    op.create_table('project_style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=200), nullable=False),
    sa.Column('book_analysis_id', sa.Integer(), nullable=True),
    sa.Column('derived_rules', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_analysis_id'], ['book_analysis_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_style_profiles_book_analysis_id'), 'project_style_profiles', ['book_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_style_profiles_id'), 'project_style_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_project_style_profiles_project_id'), 'project_style_profiles', ['project_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('research_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('query_plan_json', sa.JSON(), nullable=True),
    sa.Column('extracted_summary', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=False)
    op.create_index(op.f('ix_research_runs_project_id'), 'research_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_runs_run_id'), 'research_runs', ['run_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('story_time', sa.String(length=100), nullable=True),
    sa.Column('story_time_order', sa.Float(), nullable=True),
    sa.Column('time_type', sa.String(length=20), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_locations', sa.JSON(), nullable=True),
    sa.Column('related_items', sa.JSON(), nullable=True),
    sa.Column('is_key_event', sa.Boolean(), nullable=True),
    sa.Column('is_flashback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_chapter_id'), 'timeline_events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['agent_plans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_id'), 'agent_steps', ['id'], unique=False)
    op.create_index(op.f('ix_agent_steps_plan_id'), 'agent_steps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_table('consistency_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Enum('CHARACTER', 'POWER', 'TIMELINE', 'WORLD_SETTING', 'RELATIONSHIP', 'LOCATION', 'ITEM', name='consistencychecktype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'INFO', name='consistencyissueseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('reference_location', sa.String(length=200), nullable=True),
    sa.Column('reference_quote', sa.Text(), nullable=True),
    sa.Column('fix_suggestion', sa.Text(), nullable=True),
    sa.Column('auto_fixable', sa.Boolean(), nullable=True),
    sa.Column('auto_fix_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.Column('fixed_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_id'], ['consistency_check_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_issues_chapter_id'), 'consistency_issues', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_consistency_issues_id'), 'consistency_issues', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_issues_result_id'), 'consistency_issues', ['result_id'], unique=False)
    op.create_table('evolution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evolution_run_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evolution_run_id'], ['evolution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_logs_id'), 'evolution_logs', ['id'], unique=False)
    op.create_table('final_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('review_result_ids', sa.JSON(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('critical_issues', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('rewrite_focus', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_reviews_chapter_id'), 'final_reviews', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_final_reviews_id'), 'final_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_final_reviews_task_id'), 'final_reviews', ['task_id'], unique=False)
    op.create_table('generation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_steps_id'), 'generation_steps', ['id'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('words_written', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_log_project', 'production_logs', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_production_log_type', 'production_logs', ['log_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_production_logs_id'), 'production_logs', ['id'], unique=False)
    op.create_index(op.f('ix_production_logs_log_type'), 'production_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_production_logs_project_id'), 'production_logs', ['project_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('extracted_text_hash', sa.String(length=128), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('used_for', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_id'), 'research_sources', ['id'], unique=False)
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_role', sa.String(length=100), nullable=True),
    sa.Column('reviewer_model', sa.String(length=200), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('required_fixes', sa.JSON(), nullable=True),
    sa.Column('pass_status', sa.String(length=50), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_chapter_role', 'review_results', ['chapter_id', 'reviewer_role'], unique=False)
    op.create_index('idx_review_task', 'review_results', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_results_chapter_id'), 'review_results', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_review_results_id'), 'review_results', ['id'], unique=False)
    op.create_index(op.f('ix_review_results_reviewer_role'), 'review_results', ['reviewer_role'], unique=False)
    op.create_index(op.f('ix_review_results_task_id'), 'review_results', ['task_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('preference', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('source_feedback_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('subagent_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('input_task_ids', sa.JSON(), nullable=True),
    sa.Column('merged_output', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('provider_name', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_step_id'], ['agent_steps.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subagent_results_id'), 'subagent_results', ['id'], unique=False)
    op.create_index(op.f('ix_subagent_results_parent_step_id'), 'subagent_results', ['parent_step_id'], unique=False)
    op.create_index(op.f('ix_subagent_results_run_id'), 'subagent_results', ['run_id'], unique=False)
    op.create_table('subagent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('provider_name', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_step_id'], ['agent_steps.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subagent_tasks_id'), 'subagent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_subagent_tasks_parent_step_id'), 'subagent_tasks', ['parent_step_id'], unique=False)
    op.create_index(op.f('ix_subagent_tasks_run_id'), 'subagent_tasks', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subagent_tasks_run_id'), table_name='subagent_tasks')
    op.drop_index(op.f('ix_subagent_tasks_parent_step_id'), table_name='subagent_tasks')
    op.drop_index(op.f('ix_subagent_tasks_id'), table_name='subagent_tasks')
    op.drop_table('subagent_tasks')
    op.drop_index(op.f('ix_subagent_results_run_id'), table_name='subagent_results')
    op.drop_index(op.f('ix_subagent_results_parent_step_id'), table_name='subagent_results')
    op.drop_index(op.f('ix_subagent_results_id'), table_name='subagent_results')
    op.drop_table('subagent_results')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_review_results_task_id'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_reviewer_role'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_id'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_chapter_id'), table_name='review_results')
    op.drop_index('idx_review_task', table_name='review_results')
    op.drop_index('idx_review_chapter_role', table_name='review_results')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_production_logs_project_id'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_log_type'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_id'), table_name='production_logs')
    op.drop_index('idx_production_log_type', table_name='production_logs')
    op.drop_index('idx_production_log_project', table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_generation_steps_id'), table_name='generation_steps')
    op.drop_table('generation_steps')
    op.drop_index(op.f('ix_final_reviews_task_id'), table_name='final_reviews')
    op.drop_index(op.f('ix_final_reviews_id'), table_name='final_reviews')
    op.drop_index(op.f('ix_final_reviews_chapter_id'), table_name='final_reviews')
    op.drop_table('final_reviews')
    op.drop_index(op.f('ix_evolution_logs_id'), table_name='evolution_logs')
    op.drop_table('evolution_logs')
    op.drop_index(op.f('ix_consistency_issues_result_id'), table_name='consistency_issues')
    op.drop_index(op.f('ix_consistency_issues_id'), table_name='consistency_issues')
    op.drop_index(op.f('ix_consistency_issues_chapter_id'), table_name='consistency_issues')
    op.drop_table('consistency_issues')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_plan_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_chapter_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_research_runs_run_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_project_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_project_style_profiles_project_id'), table_name='project_style_profiles')
    op.drop_index(op.f('ix_project_style_profiles_id'), table_name='project_style_profiles')
    op.drop_index(op.f('ix_project_style_profiles_book_analysis_id'), table_name='project_style_profiles')
    op.drop_table('project_style_profiles')
    op.drop_index(op.f('ix_memory_query_logs_project_id'), table_name='memory_query_logs')
    op.drop_index(op.f('ix_memory_query_logs_id'), table_name='memory_query_logs')
    op.drop_index(op.f('ix_memory_query_logs_chapter_id'), table_name='memory_query_logs')
    op.drop_table('memory_query_logs')
    op.drop_index(op.f('ix_generation_tasks_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_foreshadow_reviews_project_id'), table_name='foreshadow_reviews')
    op.drop_index(op.f('ix_foreshadow_reviews_chapter_id'), table_name='foreshadow_reviews')
    op.drop_table('foreshadow_reviews')
    op.drop_index(op.f('ix_foreshadow_plans_project_id'), table_name='foreshadow_plans')
    op.drop_index(op.f('ix_foreshadow_plans_chapter_index'), table_name='foreshadow_plans')
    op.drop_index(op.f('ix_foreshadow_plans_chapter_id'), table_name='foreshadow_plans')
    op.drop_table('foreshadow_plans')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_evolution_runs_id'), table_name='evolution_runs')
    op.drop_table('evolution_runs')
    op.drop_index(op.f('ix_consistency_check_results_rule_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_project_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_chapter_id'), table_name='consistency_check_results')
    op.drop_table('consistency_check_results')
    op.drop_index(op.f('ix_character_consistency_logs_project_id'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_id'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_character_name'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_chapter_id'), table_name='character_consistency_logs')
    op.drop_table('character_consistency_logs')
    op.drop_index(op.f('ix_chapter_versions_id'), table_name='chapter_versions')
    op.drop_table('chapter_versions')
    op.drop_index(op.f('ix_chapter_memories_project_id'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_id'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_chapter_index'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_chapter_id'), table_name='chapter_memories')
    op.drop_index('idx_chapter_memory_project_idx', table_name='chapter_memories')
    op.drop_table('chapter_memories')
    op.drop_index(op.f('ix_agent_plans_run_id'), table_name='agent_plans')
    op.drop_index(op.f('ix_agent_plans_id'), table_name='agent_plans')
    op.drop_table('agent_plans')
    op.drop_index(op.f('ix_world_memories_project_id'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_name'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_id'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_category'), table_name='world_memories')
    op.drop_index('idx_world_memory_project_name', table_name='world_memories')
    op.drop_index('idx_world_memory_project_cat', table_name='world_memories')
    op.drop_table('world_memories')
    op.drop_index(op.f('ix_version_history_id'), table_name='version_history')
    op.drop_table('version_history')
    op.drop_index(op.f('ix_technique_cards_taxonomy_level_2'), table_name='technique_cards')
    op.drop_index(op.f('ix_technique_cards_taxonomy_level_1'), table_name='technique_cards')
    op.drop_index(op.f('ix_technique_cards_id'), table_name='technique_cards')
    op.drop_table('technique_cards')
    op.drop_index(op.f('ix_review_profiles_id'), table_name='review_profiles')
    op.drop_table('review_profiles')
    op.drop_index(op.f('ix_relationship_memories_project_id'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_id'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_character_b'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_character_a'), table_name='relationship_memories')
    op.drop_index('idx_rel_memory_project_chars', table_name='relationship_memories')
    op.drop_table('relationship_memories')
    op.drop_index(op.f('ix_provider_route_configs_role'), table_name='provider_route_configs')
    op.drop_index(op.f('ix_provider_route_configs_provider_id'), table_name='provider_route_configs')
    op.drop_index(op.f('ix_provider_route_configs_id'), table_name='provider_route_configs')
    op.drop_table('provider_route_configs')
    op.drop_index(op.f('ix_prompt_templates_role'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_prompt_evolution_runs_role'), table_name='prompt_evolution_runs')
    op.drop_index(op.f('ix_prompt_evolution_runs_policy_id'), table_name='prompt_evolution_runs')
    op.drop_index(op.f('ix_prompt_evolution_runs_id'), table_name='prompt_evolution_runs')
    op.drop_table('prompt_evolution_runs')
    op.drop_index(op.f('ix_project_playbooks_id'), table_name='project_playbooks')
    op.drop_table('project_playbooks')
    op.drop_index(op.f('ix_production_stats_project_id'), table_name='production_stats')
    op.drop_index(op.f('ix_production_stats_id'), table_name='production_stats')
    op.drop_index(op.f('ix_production_stats_date'), table_name='production_stats')
    op.drop_index('idx_production_stats_project_date', table_name='production_stats')
    op.drop_table('production_stats')
    op.drop_index(op.f('ix_production_policies_project_id'), table_name='production_policies')
    op.drop_index(op.f('ix_production_policies_id'), table_name='production_policies')
    op.drop_table('production_policies')
    op.drop_index(op.f('ix_novel_bibles_id'), table_name='novel_bibles')
    op.drop_table('novel_bibles')
    op.drop_index(op.f('ix_model_roles_id'), table_name='model_roles')
    op.drop_table('model_roles')
    op.drop_index(op.f('ix_model_call_logs_project_id'), table_name='model_call_logs')
    op.drop_index(op.f('ix_model_call_logs_id'), table_name='model_call_logs')
    op.drop_table('model_call_logs')
    op.drop_index(op.f('ix_foreshadows_status'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_setup_chapter'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_project_id'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_id'), table_name='foreshadows')
    op.drop_index('idx_foreshadow_setup_chapter', table_name='foreshadows')
    op.drop_index('idx_foreshadow_project_status', table_name='foreshadows')
    op.drop_table('foreshadows')
    op.drop_index(op.f('ix_failure_patterns_id'), table_name='failure_patterns')
    op.drop_table('failure_patterns')
    op.drop_index(op.f('ix_consistency_rules_project_id'), table_name='consistency_rules')
    op.drop_index(op.f('ix_consistency_rules_id'), table_name='consistency_rules')
    op.drop_table('consistency_rules')
    op.drop_index(op.f('ix_character_memories_project_id'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_name'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_id'), table_name='character_memories')
    op.drop_index('idx_char_memory_project_name', table_name='character_memories')
    op.drop_index('idx_char_memory_importance', table_name='character_memories')
    op.drop_table('character_memories')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_book_profiles_id'), table_name='book_profiles')
    op.drop_table('book_profiles')
    op.drop_index(op.f('ix_book_chapters_id'), table_name='book_chapters')
    op.drop_table('book_chapters')
    op.drop_index(op.f('ix_book_analysis_profiles_id'), table_name='book_analysis_profiles')
    op.drop_index(op.f('ix_book_analysis_profiles_book_id'), table_name='book_analysis_profiles')
    op.drop_table('book_analysis_profiles')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_trend_reports_platform'), table_name='trend_reports')
    op.drop_index(op.f('ix_trend_reports_id'), table_name='trend_reports')
    op.drop_index(op.f('ix_trend_reports_genre'), table_name='trend_reports')
    op.drop_table('trend_reports')
    op.drop_index(op.f('ix_story_patterns_id'), table_name='story_patterns')
    op.drop_table('story_patterns')
    op.drop_index(op.f('ix_reader_insights_insight_type'), table_name='reader_insights')
    op.drop_index(op.f('ix_reader_insights_id'), table_name='reader_insights')
    op.drop_index(op.f('ix_reader_insights_genre'), table_name='reader_insights')
    op.drop_table('reader_insights')
    op.drop_index(op.f('ix_prompt_evolution_policies_role'), table_name='prompt_evolution_policies')
    op.drop_index(op.f('ix_prompt_evolution_policies_id'), table_name='prompt_evolution_policies')
    op.drop_table('prompt_evolution_policies')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_model_providers_id'), table_name='model_providers')
    op.drop_table('model_providers')
    op.drop_index(op.f('ix_knowledge_patterns_tag'), table_name='knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_patterns_pattern_type'), table_name='knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_patterns_id'), table_name='knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_patterns_genre'), table_name='knowledge_patterns')
    op.drop_table('knowledge_patterns')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
