"""baseline

Revision ID: 7d0a239b5be7
Revises: 
Create Date: 2026-05-29 13:23:45.721188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0a239b5be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'project_id', 'provider', 'model_name', name='uix_daily_stats')
    )
    op.create_index(op.f('ix_daily_usage_stats_date'), 'daily_usage_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_usage_stats_id'), 'daily_usage_stats', ['id'], unique=False)
    op.create_index(op.f('ix_daily_usage_stats_project_id'), 'daily_usage_stats', ['project_id'], unique=False)
    op.create_table('book_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('sub_genre', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('narrative_pov', sa.String(length=50), nullable=True),
    sa.Column('pacing_type', sa.String(length=50), nullable=True),
    sa.Column('commercial_density', sa.Integer(), nullable=True),
    sa.Column('adult_level', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('reusable_skill_categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_index(op.f('ix_book_profiles_id'), 'book_profiles', ['id'], unique=False)
    op.create_table('character_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('stable_profile', sa.JSON(), nullable=True),
    sa.Column('dynamic_state', sa.JSON(), nullable=True),
    sa.Column('personality', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('last_seen_chapter', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('latest_update_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_char_memory_importance', 'character_memories', ['project_id', 'importance_score'], unique=False)
    op.create_index('idx_char_memory_project_name', 'character_memories', ['project_id', 'name'], unique=False)
    op.create_index(op.f('ix_character_memories_id'), 'character_memories', ['id'], unique=False)
    op.create_index(op.f('ix_character_memories_name'), 'character_memories', ['name'], unique=False)
    op.create_index(op.f('ix_character_memories_project_id'), 'character_memories', ['project_id'], unique=False)
    op.create_table('foreshadows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('foreshadow_type', sa.String(length=100), nullable=True),
    sa.Column('setup_chapter', sa.Integer(), nullable=True),
    sa.Column('expected_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('actual_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('setup_content', sa.Text(), nullable=True),
    sa.Column('development_notes', sa.JSON(), nullable=True),
    sa.Column('payoff_plan', sa.Text(), nullable=True),
    sa.Column('payoff_content', sa.Text(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_items', sa.JSON(), nullable=True),
    sa.Column('related_world_rules', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reader_expectation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_foreshadow_project_status', 'foreshadows', ['project_id', 'status'], unique=False)
    op.create_index('idx_foreshadow_setup_chapter', 'foreshadows', ['project_id', 'setup_chapter'], unique=False)
    op.create_index(op.f('ix_foreshadows_id'), 'foreshadows', ['id'], unique=False)
    op.create_index(op.f('ix_foreshadows_project_id'), 'foreshadows', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadows_setup_chapter'), 'foreshadows', ['setup_chapter'], unique=False)
    op.create_index(op.f('ix_foreshadows_status'), 'foreshadows', ['status'], unique=False)
    op.create_table('production_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('target_daily_words', sa.Integer(), nullable=True),
    sa.Column('target_daily_chapters', sa.Integer(), nullable=True),
    sa.Column('max_daily_cost', sa.Float(), nullable=True),
    sa.Column('max_daily_tokens', sa.Integer(), nullable=True),
    sa.Column('min_quality_score', sa.Float(), nullable=True),
    sa.Column('max_rewrite_rounds', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('auto_create_next_chapter', sa.Integer(), nullable=True),
    sa.Column('auto_pause_on_failure', sa.Integer(), nullable=True),
    sa.Column('auto_pause_on_budget', sa.Integer(), nullable=True),
    sa.Column('active_hours', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_policies_id'), 'production_policies', ['id'], unique=False)
    op.create_index(op.f('ix_production_policies_project_id'), 'production_policies', ['project_id'], unique=True)
    op.create_table('production_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('chapters_completed', sa.Integer(), nullable=True),
    sa.Column('words_written', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('rewrite_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('word_goal_achievement', sa.Float(), nullable=True),
    sa.Column('chapter_goal_achievement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_stats_project_date', 'production_stats', ['project_id', 'date'], unique=True)
    op.create_index(op.f('ix_production_stats_date'), 'production_stats', ['date'], unique=False)
    op.create_index(op.f('ix_production_stats_id'), 'production_stats', ['id'], unique=False)
    op.create_index(op.f('ix_production_stats_project_id'), 'production_stats', ['project_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables_schema', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_role'), 'prompt_templates', ['role'], unique=False)
    op.create_table('relationship_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_a', sa.String(length=200), nullable=True),
    sa.Column('character_b', sa.String(length=200), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('tension_level', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('last_changed_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_memory_project_chars', 'relationship_memories', ['project_id', 'character_a', 'character_b'], unique=False)
    op.create_index(op.f('ix_relationship_memories_character_a'), 'relationship_memories', ['character_a'], unique=False)
    op.create_index(op.f('ix_relationship_memories_character_b'), 'relationship_memories', ['character_b'], unique=False)
    op.create_index(op.f('ix_relationship_memories_id'), 'relationship_memories', ['id'], unique=False)
    op.create_index(op.f('ix_relationship_memories_project_id'), 'relationship_memories', ['project_id'], unique=False)
    op.create_table('review_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('reviewer_roles', sa.JSON(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=True),
    sa.Column('rewrite_threshold', sa.Float(), nullable=True),
    sa.Column('auto_reject_threshold', sa.Float(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('strictness', sa.Integer(), nullable=True),
    sa.Column('max_review_rounds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_profiles_id'), 'review_profiles', ['id'], unique=False)
    op.create_table('world_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_chapters', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_canon', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_world_memory_project_cat', 'world_memories', ['project_id', 'category'], unique=False)
    op.create_index('idx_world_memory_project_name', 'world_memories', ['project_id', 'name'], unique=False)
    op.create_index(op.f('ix_world_memories_category'), 'world_memories', ['category'], unique=False)
    op.create_index(op.f('ix_world_memories_id'), 'world_memories', ['id'], unique=False)
    op.create_index(op.f('ix_world_memories_name'), 'world_memories', ['name'], unique=False)
    op.create_index(op.f('ix_world_memories_project_id'), 'world_memories', ['project_id'], unique=False)
    op.create_table('chapter_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('character_changes', sa.JSON(), nullable=True),
    sa.Column('world_updates', sa.JSON(), nullable=True),
    sa.Column('relationship_changes', sa.JSON(), nullable=True),
    sa.Column('unresolved_questions', sa.JSON(), nullable=True),
    sa.Column('foreshadow_updates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_memory_project_idx', 'chapter_memories', ['project_id', 'chapter_index'], unique=False)
    op.create_index(op.f('ix_chapter_memories_chapter_id'), 'chapter_memories', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_memories_chapter_index'), 'chapter_memories', ['chapter_index'], unique=False)
    op.create_index(op.f('ix_chapter_memories_id'), 'chapter_memories', ['id'], unique=False)
    op.create_index(op.f('ix_chapter_memories_project_id'), 'chapter_memories', ['project_id'], unique=False)
    op.create_table('foreshadow_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('new_foreshadows', sa.JSON(), nullable=True),
    sa.Column('develop_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('payoff_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('must_include_lines', sa.JSON(), nullable=True),
    sa.Column('risky_foreshadow_ids', sa.JSON(), nullable=True),
    sa.Column('is_executed', sa.Integer(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadow_plans_chapter_id'), 'foreshadow_plans', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadow_plans_chapter_index'), 'foreshadow_plans', ['chapter_index'], unique=False)
    op.create_index(op.f('ix_foreshadow_plans_project_id'), 'foreshadow_plans', ['project_id'], unique=False)
    op.create_table('foreshadow_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('forgotten_foreshadows', sa.JSON(), nullable=True),
    sa.Column('premature_payoffs', sa.JSON(), nullable=True),
    sa.Column('delayed_payoffs', sa.JSON(), nullable=True),
    sa.Column('payoff_quality_issues', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('foreshadow_score', sa.Float(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadow_reviews_chapter_id'), 'foreshadow_reviews', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadow_reviews_project_id'), 'foreshadow_reviews', ['project_id'], unique=False)
    op.create_table('memory_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_query_logs_chapter_id'), 'memory_query_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_memory_query_logs_id'), 'memory_query_logs', ['id'], unique=False)
    op.create_index(op.f('ix_memory_query_logs_project_id'), 'memory_query_logs', ['project_id'], unique=False)
    op.create_table('final_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('review_result_ids', sa.JSON(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('critical_issues', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('rewrite_focus', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_reviews_chapter_id'), 'final_reviews', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_final_reviews_id'), 'final_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_final_reviews_task_id'), 'final_reviews', ['task_id'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('words_written', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_log_project', 'production_logs', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_production_log_type', 'production_logs', ['log_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_production_logs_id'), 'production_logs', ['id'], unique=False)
    op.create_index(op.f('ix_production_logs_log_type'), 'production_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_production_logs_project_id'), 'production_logs', ['project_id'], unique=False)
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_role', sa.String(length=100), nullable=True),
    sa.Column('reviewer_model', sa.String(length=200), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('required_fixes', sa.JSON(), nullable=True),
    sa.Column('pass_status', sa.String(length=50), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_chapter_role', 'review_results', ['chapter_id', 'reviewer_role'], unique=False)
    op.create_index('idx_review_task', 'review_results', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_results_chapter_id'), 'review_results', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_review_results_id'), 'review_results', ['id'], unique=False)
    op.create_index(op.f('ix_review_results_reviewer_role'), 'review_results', ['reviewer_role'], unique=False)
    op.create_index(op.f('ix_review_results_task_id'), 'review_results', ['task_id'], unique=False)
    op.add_column('generation_tasks', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('generation_tasks', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('generation_tasks', sa.Column('locked_by', sa.String(length=100), nullable=True))
    op.add_column('generation_tasks', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('generation_tasks', sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
    op.add_column('generation_tasks', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'generation_tasks', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'generation_tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('model_call_logs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_model_call_logs_project_id'), 'model_call_logs', ['project_id'], unique=False)
    op.create_foreign_key(None, 'model_call_logs', 'projects', ['project_id'], ['id'])
    op.add_column('technique_cards', sa.Column('taxonomy_level_1', sa.String(length=100), nullable=True))
    op.add_column('technique_cards', sa.Column('taxonomy_level_2', sa.String(length=100), nullable=True))
    op.add_column('technique_cards', sa.Column('scene_stage', sa.String(length=100), nullable=True))
    op.add_column('technique_cards', sa.Column('suitable_chapter_range', sa.JSON(), nullable=True))
    op.add_column('technique_cards', sa.Column('source_book_type', sa.String(length=100), nullable=True))
    op.add_column('technique_cards', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('technique_cards', sa.Column('risk_level', sa.Integer(), nullable=True))
    op.add_column('technique_cards', sa.Column('effectiveness_score', sa.Float(), nullable=True))
    op.add_column('technique_cards', sa.Column('positive_review_count', sa.Integer(), nullable=True))
    op.add_column('technique_cards', sa.Column('negative_review_count', sa.Integer(), nullable=True))
    op.add_column('technique_cards', sa.Column('used_in_chapters', sa.JSON(), nullable=True))
    op.add_column('technique_cards', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_technique_cards_taxonomy_level_1'), 'technique_cards', ['taxonomy_level_1'], unique=False)
    op.create_index(op.f('ix_technique_cards_taxonomy_level_2'), 'technique_cards', ['taxonomy_level_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technique_cards_taxonomy_level_2'), table_name='technique_cards')
    op.drop_index(op.f('ix_technique_cards_taxonomy_level_1'), table_name='technique_cards')
    op.drop_column('technique_cards', 'cluster_id')
    op.drop_column('technique_cards', 'used_in_chapters')
    op.drop_column('technique_cards', 'negative_review_count')
    op.drop_column('technique_cards', 'positive_review_count')
    op.drop_column('technique_cards', 'effectiveness_score')
    op.drop_column('technique_cards', 'risk_level')
    op.drop_column('technique_cards', 'difficulty')
    op.drop_column('technique_cards', 'source_book_type')
    op.drop_column('technique_cards', 'suitable_chapter_range')
    op.drop_column('technique_cards', 'scene_stage')
    op.drop_column('technique_cards', 'taxonomy_level_2')
    op.drop_column('technique_cards', 'taxonomy_level_1')
    op.drop_constraint(None, 'model_call_logs', type_='foreignkey')
    op.drop_index(op.f('ix_model_call_logs_project_id'), table_name='model_call_logs')
    op.drop_column('model_call_logs', 'project_id')
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'generation_tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'generation_tasks', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('generation_tasks', 'next_run_at')
    op.drop_column('generation_tasks', 'heartbeat_at')
    op.drop_column('generation_tasks', 'locked_at')
    op.drop_column('generation_tasks', 'locked_by')
    op.drop_column('generation_tasks', 'max_attempts')
    op.drop_column('generation_tasks', 'attempts')
    op.drop_index(op.f('ix_review_results_task_id'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_reviewer_role'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_id'), table_name='review_results')
    op.drop_index(op.f('ix_review_results_chapter_id'), table_name='review_results')
    op.drop_index('idx_review_task', table_name='review_results')
    op.drop_index('idx_review_chapter_role', table_name='review_results')
    op.drop_table('review_results')
    op.drop_index(op.f('ix_production_logs_project_id'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_log_type'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_id'), table_name='production_logs')
    op.drop_index('idx_production_log_type', table_name='production_logs')
    op.drop_index('idx_production_log_project', table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_final_reviews_task_id'), table_name='final_reviews')
    op.drop_index(op.f('ix_final_reviews_id'), table_name='final_reviews')
    op.drop_index(op.f('ix_final_reviews_chapter_id'), table_name='final_reviews')
    op.drop_table('final_reviews')
    op.drop_index(op.f('ix_memory_query_logs_project_id'), table_name='memory_query_logs')
    op.drop_index(op.f('ix_memory_query_logs_id'), table_name='memory_query_logs')
    op.drop_index(op.f('ix_memory_query_logs_chapter_id'), table_name='memory_query_logs')
    op.drop_table('memory_query_logs')
    op.drop_index(op.f('ix_foreshadow_reviews_project_id'), table_name='foreshadow_reviews')
    op.drop_index(op.f('ix_foreshadow_reviews_chapter_id'), table_name='foreshadow_reviews')
    op.drop_table('foreshadow_reviews')
    op.drop_index(op.f('ix_foreshadow_plans_project_id'), table_name='foreshadow_plans')
    op.drop_index(op.f('ix_foreshadow_plans_chapter_index'), table_name='foreshadow_plans')
    op.drop_index(op.f('ix_foreshadow_plans_chapter_id'), table_name='foreshadow_plans')
    op.drop_table('foreshadow_plans')
    op.drop_index(op.f('ix_chapter_memories_project_id'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_id'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_chapter_index'), table_name='chapter_memories')
    op.drop_index(op.f('ix_chapter_memories_chapter_id'), table_name='chapter_memories')
    op.drop_index('idx_chapter_memory_project_idx', table_name='chapter_memories')
    op.drop_table('chapter_memories')
    op.drop_index(op.f('ix_world_memories_project_id'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_name'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_id'), table_name='world_memories')
    op.drop_index(op.f('ix_world_memories_category'), table_name='world_memories')
    op.drop_index('idx_world_memory_project_name', table_name='world_memories')
    op.drop_index('idx_world_memory_project_cat', table_name='world_memories')
    op.drop_table('world_memories')
    op.drop_index(op.f('ix_review_profiles_id'), table_name='review_profiles')
    op.drop_table('review_profiles')
    op.drop_index(op.f('ix_relationship_memories_project_id'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_id'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_character_b'), table_name='relationship_memories')
    op.drop_index(op.f('ix_relationship_memories_character_a'), table_name='relationship_memories')
    op.drop_index('idx_rel_memory_project_chars', table_name='relationship_memories')
    op.drop_table('relationship_memories')
    op.drop_index(op.f('ix_prompt_templates_role'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_production_stats_project_id'), table_name='production_stats')
    op.drop_index(op.f('ix_production_stats_id'), table_name='production_stats')
    op.drop_index(op.f('ix_production_stats_date'), table_name='production_stats')
    op.drop_index('idx_production_stats_project_date', table_name='production_stats')
    op.drop_table('production_stats')
    op.drop_index(op.f('ix_production_policies_project_id'), table_name='production_policies')
    op.drop_index(op.f('ix_production_policies_id'), table_name='production_policies')
    op.drop_table('production_policies')
    op.drop_index(op.f('ix_foreshadows_status'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_setup_chapter'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_project_id'), table_name='foreshadows')
    op.drop_index(op.f('ix_foreshadows_id'), table_name='foreshadows')
    op.drop_index('idx_foreshadow_setup_chapter', table_name='foreshadows')
    op.drop_index('idx_foreshadow_project_status', table_name='foreshadows')
    op.drop_table('foreshadows')
    op.drop_index(op.f('ix_character_memories_project_id'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_name'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_id'), table_name='character_memories')
    op.drop_index('idx_char_memory_project_name', table_name='character_memories')
    op.drop_index('idx_char_memory_importance', table_name='character_memories')
    op.drop_table('character_memories')
    op.drop_index(op.f('ix_book_profiles_id'), table_name='book_profiles')
    op.drop_table('book_profiles')
    op.drop_index(op.f('ix_daily_usage_stats_project_id'), table_name='daily_usage_stats')
    op.drop_index(op.f('ix_daily_usage_stats_id'), table_name='daily_usage_stats')
    op.drop_index(op.f('ix_daily_usage_stats_date'), table_name='daily_usage_stats')
    op.drop_table('daily_usage_stats')
    # ### end Alembic commands ###
