"""
Add book analysis models (B3)

Revision ID: add_book_analysis_models
Revises: cf572852293f
Create Date: 2025-05-29
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_book_analysis_models'
down_revision = 'cf572852293f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_analysis_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('total_chapters', sa.Integer(), nullable=True),
        sa.Column('total_words', sa.Integer(), nullable=True),
        sa.Column('avg_chapter_words', sa.Float(), nullable=True),
        sa.Column('chapter_word_std', sa.Float(), nullable=True),
        sa.Column('hook_rate', sa.Float(), nullable=True),
        sa.Column('cliffhanger_rate', sa.Float(), nullable=True),
        sa.Column('payoff_cadence_chapters', sa.Float(), nullable=True),
        sa.Column('emotion_curve', sa.JSON(), nullable=True),
        sa.Column('pacing_rules', sa.JSON(), nullable=True),
        sa.Column('character_arc_patterns', sa.JSON(), nullable=True),
        sa.Column('plot_structure', sa.JSON(), nullable=True),
        sa.Column('satisfaction_peaks', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_analysis_profiles_book_id'), 'book_analysis_profiles', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_analysis_profiles_id'), 'book_analysis_profiles', ['id'], unique=False)

    op.create_table('project_style_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('profile_name', sa.String(length=200), nullable=False),
        sa.Column('book_analysis_id', sa.Integer(), nullable=True),
        sa.Column('derived_rules', sa.JSON(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['book_analysis_id'], ['book_analysis_profiles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_style_profiles_book_analysis_id'), 'project_style_profiles', ['book_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_style_profiles_id'), 'project_style_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_project_style_profiles_project_id'), 'project_style_profiles', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_style_profiles_project_id'), table_name='project_style_profiles')
    op.drop_index(op.f('ix_project_style_profiles_id'), table_name='project_style_profiles')
    op.drop_index(op.f('ix_project_style_profiles_book_analysis_id'), table_name='project_style_profiles')
    op.drop_table('project_style_profiles')
    op.drop_index(op.f('ix_book_analysis_profiles_id'), table_name='book_analysis_profiles')
    op.drop_index(op.f('ix_book_analysis_profiles_book_id'), table_name='book_analysis_profiles')
    op.drop_table('book_analysis_profiles')
    # ### end Alembic commands ###
