"""
Add consistency check models (B4)

Revision ID: add_consistency_models
Revises: add_book_analysis_models
Create Date: 2025-05-29
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_consistency_models'
down_revision = 'add_book_analysis_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consistency_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('rule_type', sa.Enum('character', 'power', 'timeline', 'world_setting', 'relationship', 'location', 'item', name='consistencychecktype'), nullable=False),
        sa.Column('rule_name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rule_config', sa.JSON(), nullable=True),
        sa.Column('auto_check', sa.Boolean(), nullable=True),
        sa.Column('check_frequency', sa.String(length=20), nullable=True),
        sa.Column('alert_threshold', sa.Enum('critical', 'major', 'minor', 'info', name='consistencyissueseverity'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_rules_id'), 'consistency_rules', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_rules_project_id'), 'consistency_rules', ['project_id'], unique=False)

    op.create_table('consistency_check_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('chapter_id', sa.Integer(), nullable=True),
        sa.Column('checked_chapters', sa.JSON(), nullable=True),
        sa.Column('check_scope', sa.String(length=50), nullable=True),
        sa.Column('total_issues', sa.Integer(), nullable=True),
        sa.Column('critical_count', sa.Integer(), nullable=True),
        sa.Column('major_count', sa.Integer(), nullable=True),
        sa.Column('minor_count', sa.Integer(), nullable=True),
        sa.Column('info_count', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['rule_id'], ['consistency_rules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_check_results_chapter_id'), 'consistency_check_results', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_id'), 'consistency_check_results', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_project_id'), 'consistency_check_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_consistency_check_results_rule_id'), 'consistency_check_results', ['rule_id'], unique=False)

    op.create_table('consistency_issues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('result_id', sa.Integer(), nullable=False),
        sa.Column('chapter_id', sa.Integer(), nullable=True),
        sa.Column('issue_type', sa.Enum('character', 'power', 'timeline', 'world_setting', 'relationship', 'location', 'item', name='consistencychecktype'), nullable=False),
        sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'info', name='consistencyissueseverity'), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('quote', sa.Text(), nullable=True),
        sa.Column('expected_value', sa.Text(), nullable=True),
        sa.Column('actual_value', sa.Text(), nullable=True),
        sa.Column('reference_location', sa.String(length=200), nullable=True),
        sa.Column('reference_quote', sa.Text(), nullable=True),
        sa.Column('fix_suggestion', sa.Text(), nullable=True),
        sa.Column('auto_fixable', sa.Boolean(), nullable=True),
        sa.Column('auto_fix_prompt', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('fixed_at', sa.DateTime(), nullable=True),
        sa.Column('fixed_by', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['result_id'], ['consistency_check_results.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_issues_chapter_id'), 'consistency_issues', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_consistency_issues_id'), 'consistency_issues', ['id'], unique=False)
    op.create_index(op.f('ix_consistency_issues_result_id'), 'consistency_issues', ['result_id'], unique=False)

    op.create_table('character_consistency_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('character_name', sa.String(length=100), nullable=False),
        sa.Column('chapter_id', sa.Integer(), nullable=False),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.Column('changed_fields', sa.JSON(), nullable=True),
        sa.Column('change_type', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_consistency_logs_chapter_id'), 'character_consistency_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_character_name'), 'character_consistency_logs', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_id'), 'character_consistency_logs', ['id'], unique=False)
    op.create_index(op.f('ix_character_consistency_logs_project_id'), 'character_consistency_logs', ['project_id'], unique=False)

    op.create_table('timeline_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('chapter_id', sa.Integer(), nullable=True),
        sa.Column('event_name', sa.String(length=200), nullable=False),
        sa.Column('event_description', sa.Text(), nullable=True),
        sa.Column('story_time', sa.String(length=100), nullable=True),
        sa.Column('story_time_order', sa.Float(), nullable=True),
        sa.Column('time_type', sa.String(length=20), nullable=True),
        sa.Column('related_characters', sa.JSON(), nullable=True),
        sa.Column('related_locations', sa.JSON(), nullable=True),
        sa.Column('related_items', sa.JSON(), nullable=True),
        sa.Column('is_key_event', sa.Boolean(), nullable=True),
        sa.Column('is_flashback', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_chapter_id'), 'timeline_events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_chapter_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_character_consistency_logs_project_id'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_id'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_character_name'), table_name='character_consistency_logs')
    op.drop_index(op.f('ix_character_consistency_logs_chapter_id'), table_name='character_consistency_logs')
    op.drop_table('character_consistency_logs')
    op.drop_index(op.f('ix_consistency_issues_result_id'), table_name='consistency_issues')
    op.drop_index(op.f('ix_consistency_issues_id'), table_name='consistency_issues')
    op.drop_index(op.f('ix_consistency_issues_chapter_id'), table_name='consistency_issues')
    op.drop_table('consistency_issues')
    op.drop_index(op.f('ix_consistency_check_results_rule_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_project_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_id'), table_name='consistency_check_results')
    op.drop_index(op.f('ix_consistency_check_results_chapter_id'), table_name='consistency_check_results')
    op.drop_table('consistency_check_results')
    op.drop_index(op.f('ix_consistency_rules_project_id'), table_name='consistency_rules')
    op.drop_index(op.f('ix_consistency_rules_id'), table_name='consistency_rules')
    op.drop_table('consistency_rules')
    # ### end Alembic commands ###
